name: cd
on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment (dev|test|prod)
        required: true
        default: dev
  push:
    branches:
    - main
    paths:
    - source
jobs:
  continuous-delivery:
    runs-on: ubuntu-latest
    env:
      ENV_PREFIX: "${{ github.event.inputs.env == '' && 'dev' || github.event.inputs.env }}"
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SCM_CREDS }}
    - name: Upgrade bicep
      run: az bicep upgrade
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build app
      run: |
        dotnet build ./source/ExtractorFunc -c Release -o '${{ github.workspace }}/published'
        pubProfile=$(az functionapp deployment list-publishing-profiles -g "${{ env.ENV_PREFIX }}-rg-${{ secrets.AZURE_WORKLOAD }}-${{ secrets.AZURE_RG_LOC }}" -n "${{ env.ENV_PREFIX }}-app-func${{ secrets.AZURE_WORKLOAD }}-${{ secrets.AZURE_RG_LOC }}" --query "[?publishMethod=='ZipDeploy'] | [0]")
        echo "::add-mask::$pubProfile"
        echo PUB_PROFILE=$pubProfile >> $GITHUB_ENV
    - name: Publish func
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.ENV_PREFIX }}-app-func${{ secrets.AZURE_WORKLOAD }}-${{ secrets.AZURE_RG_LOC }}
        package: '${{ github.workspace }}/published'
        publish-profile: ${{ env.PUB_PROFILE }}