name: cd
on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment (dev|test|prod)
        required: true
        default: dev
  push:
    paths:
    - source
jobs:
  continuous-delivery:
    runs-on: ubuntu-latest
    env:
      ENV_PREFIX: "${{ github.event.inputs.env == '' && 'dev' || github.event.inputs.env }}"
    steps:
    - uses: actions/checkout@v3