name: CD Extractor Func
on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment (dev|test|prod)
        required: true
        default: dev
  workflow_run:
    workflows:
    - CI Extractor Func
    types:
    - completed
    branches:
    - main
    paths:
    - source/ExtractorFunc/**
jobs:
  continuous-delivery:
    runs-on: ubuntu-latest
    env:
      ENV_PREFIX: ${{ github.event.inputs.env == '' && 'dev' || github.event.inputs.env }}
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SCM_CREDS }}
    - name: Upgrade bicep
      run: az bicep upgrade
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build app
      run: |
        dotnet build ./source/ExtractorFunc -c Release -o '${{ github.workspace }}/published'
        pubProfileXml=$(az functionapp deployment list-publishing-profiles -g "${{ env.ENV_PREFIX }}-rg-${{ secrets.AZURE_WORKLOAD }}-${{ secrets.AZURE_RG_LOC }}" -n "${{ env.ENV_PREFIX }}-app-func${{ secrets.AZURE_WORKLOAD }}-${{ secrets.AZURE_RG_LOC }}" --xml)
        echo "::add-mask::$pubProfileXml"
        echo PUB_PROFILE_XML=$pubProfileXml >> $GITHUB_ENV
    - name: Publish func
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.ENV_PREFIX }}-app-func${{ secrets.AZURE_WORKLOAD }}-${{ secrets.AZURE_RG_LOC }}
        package: '${{ github.workspace }}/published'
        publish-profile: ${{ env.PUB_PROFILE_XML }}