name: CI Extractor Func
on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment (dev|test|prod)
        required: true
        default: dev
  push:
    paths:
    - source/ExtractorFunc/**
jobs:
  run_ci:
    runs-on: ubuntu-latest
    env:
      ENV_PREFIX: ${{ github.event.inputs.env == '' && 'dev' || github.event.inputs.env }}
      STAGING_DIR: ${{ github.workspace }}/drop
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Run tests and related
      run: |
        cd ./source/ExtractorFunc
        dotnet tool restore
        dotnet test --collect:"XPlat Code Coverage"
        dotnet reportgenerator -targetdir:'${{ env.STAGING_DIR }}/coveragereport' -reports:**/coverage.cobertura.xml -reporttypes:"html"
    - name: Drop artifact - coveragereport
      uses: actions/upload-artifact@v3
      with:
        name: coveragereport
        path: ${{ env.STAGING_DIR }}/coveragereport
    - name: Save outputs for subsequent workflows 
      run: echo '{"env":"${{ env.ENV_PREFIX }}"}' > ${{ env.STAGING_DIR }}/outputs.json
    - name: Drop artifact - action outputs
      uses: actions/upload-artifact@v3
      with:
        name: outputs
        path: ${{ env.STAGING_DIR }}/outputs.json