name: deliver
on:
  push:
    branches:
    - main
    paths:
    - iac/**
    - source/**
  # testing purposes: shouldnt need workflow_dispatch at all! :D
  workflow_dispatch:
jobs:
  call_test:
    uses: ./.github/workflows/test.yml
  deliver:
    needs: call_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Stage iac (bicep)
      run: mkdir -p ./drop/deliverable && cp -r ./iac $_
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Stage source (extractor func)
      run: mkdir -p ./drop/deliverable/source && dotnet build ./source/ExtractorFunc -c Release -o $_/extractorfunc
    - name: Upload deliverables
      uses: actions/upload-artifact@v3
      with:
        name: 'delivery-${{ github.run_number }}'
        path: ${{ github.workspace }}/drop/deliverable
  call_deploy:
    needs: deliver
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      delivery: ${{ fromJson(github.run_number) }}
      environment: dev
