name: deploy
on:
  workflow_call:
    inputs:
      delivery:
        description: Delivery ref no.
        type: number
        required: true
      environment:
        description: Environment prefix
        type: string
        required: true
      ci_call:
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      delivery:
        description: Delivery ref no.
        type: number
        required: true
      environment:
        description: Environment prefix
        type: string
        required: true
jobs:
  fetch_deployables:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts from the original delivery
      if: inputs.ci_call != true
      # https://github.com/dawidd6/action-download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: deliver.yml
        branch: main
        run_number: ${{ inputs.delivery }}
        path: deliverable
        skip_unpack: true
    - name: Download iac artifact from current
      if: inputs.ci_call == true
      uses: actions/download-artifact@v3
      with:
        name: 'iac-${{ inputs.delivery }}'
        path: deliverable/iac-${{ inputs.delivery }}
    - name: Download source artifact from current
      if: inputs.ci_call == true
      uses: actions/download-artifact@v3
      with:
        name: 'source-${{ inputs.delivery }}'
        path: deliverable/source-${{ inputs.delivery }}
  deploy_iac:
    needs: fetch_deployables
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        cd deliverable
        dir
