name: deploy
on:
  workflow_call:
    inputs:
      delivery:
        description: Delivery ref no.
        type: number
        required: true
      environment:
        description: Environment prefix
        type: string
        required: true
      ci_call:
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      delivery:
        description: Delivery ref no.
        type: number
        required: true
      environment:
        description: Environment prefix
        type: string
        required: true
jobs:
  check_delivery:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve catalog delivery
      if: inputs.ci_call != true
      # https://github.com/dawidd6/action-download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: deliver.yml
        branch: main
        run_number: ${{ inputs.delivery }}
        name: 'delivery-${{ inputs.delivery }}'
        path: deliverable
    - name: Re-up delivery from catalog -> current
      if: inputs.ci_call != true
      uses: actions/upload-artifact@v3
      with:
        name: 'delivery-${{ inputs.delivery }}'
        path: deliverable
  deploy:
    needs: check_delivery
    runs-on: ubuntu-latest
    steps:
    - name: Get deliverables
      uses: actions/download-artifact@v3
      with:
        name: 'delivery-${{ inputs.delivery }}'
        path: deliverable
    - name: Get shas
      run: |
        sha256sum deliverable/iac/bicep.tar.gz
        sha256sum deliverable/source/extractor.tar.gz