name: deploy
on:
  workflow_call:
    inputs:
      delivery:
        description: Delivery ref no.
        type: string
        required: true
      environment:
        description: Environment prefix
        type: string
        required: true
  workflow_dispatch:
    inputs:
      delivery:
        description: Delivery ref no.
        type: string
        required: true
      environment:
        description: Environment prefix
        type: string
        required: true
jobs:
  fetch_deployables:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: deliver.yml
        branch: main
        run_number: ${{ github.event.inputs.delivery }}
        name: 'delivery-${{ github.event.inputs.delivery }}'
        path: delivery
    
