name: deploy
on:
  workflow_call:
    inputs:
      delivery:
        description: Delivery ref no.
        type: number
        required: true
      environment:
        description: Environment prefix
        type: string
        required: true # OPTIONS: DEV
      ci_call:
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      delivery:
        description: Delivery ref no.
        type: number
        required: true
      environment:
        description: Environment prefix
        type: string
        required: true # OPTIONS: TEST, UAT, PROD
jobs:
  check_delivery:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve catalog delivery
      if: inputs.ci_call != true
      # https://github.com/dawidd6/action-download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: deliver.yml
        branch: main
        run_number: ${{ inputs.delivery }}
        name: 'delivery-${{ inputs.delivery }}'
        path: deliverable
    - name: Re-up delivery from catalog -> current
      if: inputs.ci_call != true
      uses: actions/upload-artifact@v3
      with:
        name: 'delivery-${{ inputs.delivery }}'
        path: deliverable
  deploy:
    needs: check_delivery
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SCM_CREDS }}
    - name: Upgrade AZ Bicep
      run: az bicep upgrade
    - name: Get deliverables
      uses: actions/download-artifact@v3
      with:
        name: 'delivery-${{ inputs.delivery }}'
        path: deliverable
    - name: Get shas
      run: |
        echo SHA_IAC_BICEP=$(sha256sum deliverable/iac/bicep.tar.gz | cut -b 1-64) >> $GITHUB_ENV
        echo SHA_SRC_EXTRACTOR=$(sha256sum deliverable/source/extractor.tar.gz | cut -b 1-64) >> $GITHUB_ENV
    - id: get_map
      name: Get map
      continue-on-error: true
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: ${{ inputs.ci_call == true && 'deliver.yml' || 'deploy.yml' }}
        workflow_conclusion: success
        branch: main
        run_number: ${{ inputs.ci_call == true && inputs.delivery || '' }}
        name: ${{ inputs.ci_call == true && 'deployment_map_ci' || 'deployment_map' }}
        path: deployment_map
    - id: read_map
      name: Read map
      run: |
        map="{ ${{ inputs.environment }}: { } }"
        if [ '${{ steps.get_map.outcome }}' == 'success' ]; then
          map=$(<deployment_map/deployment_map.json)
        fi
        echo "::set-output name=map::$map"
    # Deploy iac/bicep
    - name: Deploy iac/bicep [0] - confirm
      run: echo "Thumbprint changed? ${{ fromJson(steps.read_map.outputs.map)[inputs.environment].iac_bicep != '${{ env.SHA_IAC_BICEP }}' }}"
    - name: Deploy iac/bicep [1] - extract
      if: fromJson(steps.read_map.outputs.map)[inputs.environment].iac_bicep != '${{ env.SHA_IAC_BICEP }}'
      run: mkdir -p extract/iac && tar xfz deliverable/iac/bicep.tar.gz -C $_
    # - name: Deploy iac/bicep [2] - deploy from template
    #   if: fromJson(steps.read_map.outputs.map)[inputs.environment].iac_bicep != '${{ env.SHA_IAC_BICEP }}'
    #   uses: azure/arm-deploy@v1
    #   with:
    #     subscriptionId: ${{ secrets.AZURE_SUB_ID }}
    #     resourceGroupName: ${{ inputs.environment }}-rg-${{ secrets.AZURE_WORKLOAD }}-${{ secrets.AZURE_RG_LOC }}
    #     template: extract/iac/main.bicep
    #     parameters:
    #       sqlConnection=blort-sql
    #       appInsightsConnection=${{ secrets.AZURE_INSIGHTS }}
    #       sourceDocsStorageAccountName=${{ inputs.environment }}stgsharedweu
    #       exportBlobStorageAccountName=${{ inputs.environment }}stgsharedweu
    #       exportBlobContainerName=export

    - name: Merge deployment map
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const merged = { ...${{ steps.read_map.outputs.map }}, ${{ inputs.environment }}: {
            'iac_bicep': '${{ env.SHA_IAC_BICEP }}',
            'src_extractor': '${{ env.SHA_SRC_EXTRACTOR }}'
          }};

          console.log(JSON.stringify(merged).length);

          fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/deployment_map.json`, Buffer.from(JSON.stringify(merged)));
    - name: Upload deployment map
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.ci_call == true && 'deployment_map_ci' || 'deployment_map' }}
        path: deployment_map.json 