name: deploy
on:
  workflow_call:
    inputs:
      delivery:
        description: Delivery ref no.
        type: number
        required: true
      environment:
        description: Environment prefix
        type: string
        required: true
      ci_call:
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      delivery:
        description: Delivery ref no.
        type: number
        required: true
      environment:
        description: Environment prefix
        type: string
        required: true
jobs:
  catalog_deploy:
    if: inputs.ci_call != true
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve all deliverables
      # https://github.com/dawidd6/action-download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: deliver.yml
        branch: main
        run_number: ${{ inputs.delivery }}
        path: deliverable
    - name: Inspect IaC (THIS IS A TEST!)
      run: cd deliverable/iac-${{ inputs.delivery }} && ls
    - name: Inspect Source (THIS IS A TEST!)
      run: cd deliverable/source-${{ inputs.delivery }} && ls
  ci_deploy:
    if: inputs.ci_call == true
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve iac deliverables
      uses: actions/download-artifact@v3
      with:
        name: 'iac-${{ inputs.delivery }}'
        path: deliverable/iac-${{ inputs.delivery }}
    - name: Retrieve source deliverables
      uses: actions/download-artifact@v3
      with:
        name: 'source-${{ inputs.delivery }}'
        path: deliverable/source-${{ inputs.delivery }}
    - name: Inspect IaC (THIS IS A TEST!)
      run: cd deliverable/iac-${{ inputs.delivery }} && ls
    - name: Inspect Source (THIS IS A TEST!)
      run: cd deliverable/source-${{ inputs.delivery }} && ls