name: deploy
on:
  workflow_call:
    inputs:
      delivery:
        description: Delivery ref no.
        type: number
        required: true
      environment:
        description: Environment prefix
        type: string
        required: true
      ci_call:
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      delivery:
        description: Delivery ref no.
        type: number
        required: true
      environment:
        description: Environment prefix
        type: string
        required: true
jobs:
  fetch_prior_deployables:
    if: !inputs.ci_call
    runs-on: ubuntu-latest
    steps:
    - name: Download prior artifact
      # https://github.com/dawidd6/action-download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: deliver.yml
        branch: main
        run_number: ${{ inputs.delivery }}
        name: 'delivery-${{ inputs.delivery }}'
        path: delivery
  fetch_ci_deployables:
    if: inputs.ci_call
    runs-on: ubuntu-latest
    steps:
    - name: Download current artifact
      uses: actions/download-artifact@v3
      with:
        name: 'delivery-${{ inputs.delivery }}'
        path: delivery
        
  
